export const COUNTRY_NAMES: Record<string, string> = {
  'US': 'United States',
  'CN': 'China',
  'JP': 'Japan',
  'DE': 'Germany',
  'IN': 'India',
  'GB': 'United Kingdom',
  'FR': 'France',
  'IT': 'Italy',
  'BR': 'Brazil',
  'CA': 'Canada',
  'KR': 'South Korea',
  'RU': 'Russia',
  'AU': 'Australia',
  'ES': 'Spain',
  'MX': 'Mexico',
  'ID': 'Indonesia',
  'NL': 'Netherlands',
  'SA': 'Saudi Arabia',
  'TR': 'Turkey',
  'CH': 'Switzerland',
  'TW': 'Taiwan',
  'BE': 'Belgium',
  'IE': 'Ireland',
  'IL': 'Israel',
  'NO': 'Norway',
  'AE': 'United Arab Emirates',
  'EG': 'Egypt',
  'NG': 'Nigeria',
  'ZA': 'South Africa',
  'AR': 'Argentina',
  'TH': 'Thailand',
  'SG': 'Singapore',
  'MY': 'Malaysia',
  'PH': 'Philippines',
  'CL': 'Chile',
  'PK': 'Pakistan',
  'BD': 'Bangladesh',
  'VN': 'Vietnam',
  'CO': 'Colombia',
  'PL': 'Poland',
  'SE': 'Sweden',
  'AT': 'Austria',
  'DK': 'Denmark',
  'FI': 'Finland',
  'CZ': 'Czech Republic',
  'PT': 'Portugal',
  'GR': 'Greece',
  'NZ': 'New Zealand',
  'HU': 'Hungary',
  'RO': 'Romania'
};

export function getCountryName(code: string): string {
  return COUNTRY_NAMES[code] || code;
}
