export const getCountryFlag = (countryCode: string): string => {
  const flags: Record<string, string> = {
    'US': '🇺🇸',
    'GB': '🇬🇧',
    'CA': '🇨🇦',
    'AU': '🇦🇺',
    'DE': '🇩🇪',
    'FR': '🇫🇷',
    'ES': '🇪🇸',
    'IT': '🇮🇹',
    'BR': '🇧🇷',
    'MX': '🇲🇽',
    'AR': '🇦🇷',
    'IN': '🇮🇳',
    'PK': '🇵🇰',
    'BD': '🇧🇩',
    'ID': '🇮🇩',
    'PH': '🇵🇭',
    'JP': '🇯🇵',
    'KR': '🇰🇷',
    'CN': '🇨🇳',
    'TH': '🇹🇭',
    'VN': '🇻🇳',
    'MY': '🇲🇾',
    'SG': '🇸🇬',
    'NG': '🇳🇬',
    'ZA': '🇿🇦',
    'KE': '🇰🇪',
    'GH': '🇬🇭',
    'EG': '🇪🇬',
    'MA': '🇲🇦',
    'TZ': '🇹🇿',
    'UG': '🇺🇬',
    'ET': '🇪🇹',
    'RU': '🇷🇺',
    'TR': '🇹🇷',
    'PL': '🇵🇱',
    'UA': '🇺🇦',
    'NL': '🇳🇱',
    'BE': '🇧🇪',
    'SE': '🇸🇪',
    'NO': '🇳🇴',
    'DK': '🇩🇰',
    'FI': '🇫🇮',
    'CH': '🇨🇭',
    'AT': '🇦🇹',
    'PT': '🇵🇹',
    'GR': '🇬🇷',
    'CZ': '🇨🇿',
    'HU': '🇭🇺',
    'RO': '🇷🇴',
    'BG': '🇧🇬',
    'HR': '🇭🇷',
    'RS': '🇷🇸',
    'SI': '🇸🇮',
    'SK': '🇸🇰',
    'LT': '🇱🇹',
    'LV': '🇱🇻',
    'EE': '🇪🇪',
    'IE': '🇮🇪',
    'IS': '🇮🇸',
    'LU': '🇱🇺',
    'MT': '🇲🇹',
    'CY': '🇨🇾',
    'CO': '🇨🇴',
    'CL': '🇨🇱',
    'PE': '🇵🇪',
    'VE': '🇻🇪',
    'EC': '🇪🇨',
    'BO': '🇧🇴',
    'PY': '🇵🇾',
    'UY': '🇺🇾',
    'CR': '🇨🇷',
    'PA': '🇵🇦',
    'GT': '🇬🇹',
    'SV': '🇸🇻',
    'HN': '🇭🇳',
    'NI': '🇳🇮',
    'BZ': '🇧🇿',
    'JM': '🇯🇲',
    'TT': '🇹🇹',
    'BB': '🇧🇧',
    'GD': '🇬🇩',
    'LC': '🇱🇨',
    'VC': '🇻🇨',
    'DM': '🇩🇲',
    'AG': '🇦🇬',
    'KN': '🇰🇳',
    'BS': '🇧🇸',
    'CU': '🇨🇺',
    'DO': '🇩🇴',
    'HT': '🇭🇹',
    'PR': '🇵🇷',
    'NZ': '🇳🇿',
    'FJ': '🇫🇯',
    'PG': '🇵🇬',
    'SB': '🇸🇧',
    'VU': '🇻🇺',
    'NC': '🇳🇨',
    'PF': '🇵🇫',
    'WS': '🇼🇸',
    'TO': '🇹🇴',
    'KI': '🇰🇮',
    'TV': '🇹🇻',
    'NR': '🇳🇷',
    'PW': '🇵🇼',
    'FM': '🇫🇲',
    'MH': '🇲🇭',
    'IL': '🇮🇱',
    'JO': '🇯🇴',
    'LB': '🇱🇧',
    'SY': '🇸🇾',
    'IQ': '🇮🇶',
    'IR': '🇮🇷',
    'AF': '🇦🇫',
    'SA': '🇸🇦',
    'AE': '🇦🇪',
    'QA': '🇶🇦',
    'BH': '🇧🇭',
    'KW': '🇰🇼',
    'OM': '🇴🇲',
    'YE': '🇾🇪',
    'LK': '🇱🇰',
    'MV': '🇲🇻',
    'BT': '🇧🇹',
    'NP': '🇳🇵',
    'MM': '🇲🇲',
    'LA': '🇱🇦',
    'KH': '🇰🇭',
    'BN': '🇧🇳',
    'TL': '🇹🇱',
    'MN': '🇲🇳',
    'KZ': '🇰🇿',
    'UZ': '🇺🇿',
    'TM': '🇹🇲',
    'KG': '🇰🇬',
    'TJ': '🇹🇯',
    'GE': '🇬🇪',
    'AM': '🇦🇲',
    'AZ': '🇦🇿',
    'BY': '🇧🇾',
    'MD': '🇲🇩',
    'AL': '🇦🇱',
    'ME': '🇲🇪',
    'BA': '🇧🇦',
    'MK': '🇲🇰',
    'XK': '🇽🇰',
    'LY': '🇱🇾',
    'TN': '🇹🇳',
    'DZ': '🇩🇿',
    'SD': '🇸🇩',
    'SS': '🇸🇸',
    'ER': '🇪🇷',
    'DJ': '🇩🇯',
    'SO': '🇸🇴',
    'MW': '🇲🇼',
    'ZM': '🇿🇲',
    'ZW': '🇿🇼',
    'BW': '🇧🇼',
    'NA': '🇳🇦',
    'SZ': '🇸🇿',
    'LS': '🇱🇸',
    'MG': '🇲🇬',
    'MU': '🇲🇺',
    'SC': '🇸🇨',
    'KM': '🇰🇲',
    'CV': '🇨🇻',
    'ST': '🇸🇹',
    'GQ': '🇬🇶',
    'GA': '🇬🇦',
    'CG': '🇨🇬',
    'CD': '🇨🇩',
    'CF': '🇨🇫',
    'TD': '🇹🇩',
    'CM': '🇨🇲',
    'BJ': '🇧🇯',
    'TG': '🇹🇬',
    'BF': '🇧🇫',
    'CI': '🇨🇮',
    'LR': '🇱🇷',
    'SL': '🇸🇱',
    'GN': '🇬🇳',
    'GW': '🇬🇼',
    'SN': '🇸🇳',
    'GM': '🇬🇲',
    'ML': '🇲🇱',
    'MR': '🇲🇷',
    'NE': '🇳🇪'
  };
  
  return flags[countryCode] || '🏳️';
};

export const getCountryName = (countryCode: string): string => {
  const countries: Record<string, string> = {
    'US': 'United States',
    'GB': 'United Kingdom',
    'CA': 'Canada',
    'AU': 'Australia',
    'DE': 'Germany',
    'FR': 'France',
    'ES': 'Spain',
    'IT': 'Italy',
    'BR': 'Brazil',
    'MX': 'Mexico',
    'AR': 'Argentina',
    'IN': 'India',
    'PK': 'Pakistan',
    'BD': 'Bangladesh',
    'ID': 'Indonesia',
    'PH': 'Philippines',
    'JP': 'Japan',
    'KR': 'South Korea',
    'CN': 'China',
    'TH': 'Thailand',
    'VN': 'Vietnam',
    'MY': 'Malaysia',
    'SG': 'Singapore',
    'NG': 'Nigeria',
    'ZA': 'South Africa',
    'KE': 'Kenya',
    'GH': 'Ghana',
    'EG': 'Egypt',
    'MA': 'Morocco',
    'TZ': 'Tanzania',
    'UG': 'Uganda',
    'ET': 'Ethiopia',
    'RU': 'Russia',
    'TR': 'Turkey',
    'PL': 'Poland',
    'UA': 'Ukraine',
    'NL': 'Netherlands',
    'BE': 'Belgium',
    'SE': 'Sweden',
    'NO': 'Norway',
    'DK': 'Denmark',
    'FI': 'Finland',
    'CH': 'Switzerland',
    'AT': 'Austria',
    'PT': 'Portugal',
    'GR': 'Greece',
    'CZ': 'Czech Republic',
    'HU': 'Hungary',
    'RO': 'Romania',
    'BG': 'Bulgaria',
    'HR': 'Croatia',
    'RS': 'Serbia',
    'SI': 'Slovenia',
    'SK': 'Slovakia',
    'LT': 'Lithuania',
    'LV': 'Latvia',
    'EE': 'Estonia',
    'IE': 'Ireland',
    'IS': 'Iceland',
    'LU': 'Luxembourg',
    'MT': 'Malta',
    'CY': 'Cyprus',
    'CO': 'Colombia',
    'CL': 'Chile',
    'PE': 'Peru',
    'VE': 'Venezuela',
    'EC': 'Ecuador',
    'BO': 'Bolivia',
    'PY': 'Paraguay',
    'UY': 'Uruguay',
    'CR': 'Costa Rica',
    'PA': 'Panama',
    'GT': 'Guatemala',
    'SV': 'El Salvador',
    'HN': 'Honduras',
    'NI': 'Nicaragua',
    'BZ': 'Belize',
    'JM': 'Jamaica',
    'TT': 'Trinidad and Tobago',
    'BB': 'Barbados',
    'GD': 'Grenada',
    'LC': 'Saint Lucia',
    'VC': 'Saint Vincent and the Grenadines',
    'DM': 'Dominica',
    'AG': 'Antigua and Barbuda',
    'KN': 'Saint Kitts and Nevis',
    'BS': 'Bahamas',
    'CU': 'Cuba',
    'DO': 'Dominican Republic',
    'HT': 'Haiti',
    'PR': 'Puerto Rico',
    'NZ': 'New Zealand',
    'FJ': 'Fiji',
    'PG': 'Papua New Guinea',
    'SB': 'Solomon Islands',
    'VU': 'Vanuatu',
    'NC': 'New Caledonia',
    'PF': 'French Polynesia',
    'WS': 'Samoa',
    'TO': 'Tonga',
    'KI': 'Kiribati',
    'TV': 'Tuvalu',
    'NR': 'Nauru',
    'PW': 'Palau',
    'FM': 'Micronesia',
    'MH': 'Marshall Islands',
    'IL': 'Israel',
    'JO': 'Jordan',
    'LB': 'Lebanon',
    'SY': 'Syria',
    'IQ': 'Iraq',
    'IR': 'Iran',
    'AF': 'Afghanistan',
    'SA': 'Saudi Arabia',
    'AE': 'United Arab Emirates',
    'QA': 'Qatar',
    'BH': 'Bahrain',
    'KW': 'Kuwait',
    'OM': 'Oman',
    'YE': 'Yemen',
    'LK': 'Sri Lanka',
    'MV': 'Maldives',
    'BT': 'Bhutan',
    'NP': 'Nepal',
    'MM': 'Myanmar',
    'LA': 'Laos',
    'KH': 'Cambodia',
    'BN': 'Brunei',
    'TL': 'East Timor',
    'MN': 'Mongolia',
    'KZ': 'Kazakhstan',
    'UZ': 'Uzbekistan',
    'TM': 'Turkmenistan',
    'KG': 'Kyrgyzstan',
    'TJ': 'Tajikistan',
    'GE': 'Georgia',
    'AM': 'Armenia',
    'AZ': 'Azerbaijan',
    'BY': 'Belarus',
    'MD': 'Moldova',
    'AL': 'Albania',
    'ME': 'Montenegro',
    'BA': 'Bosnia and Herzegovina',
    'MK': 'North Macedonia',
    'XK': 'Kosovo',
    'LY': 'Libya',
    'TN': 'Tunisia',
    'DZ': 'Algeria',
    'SD': 'Sudan',
    'SS': 'South Sudan',
    'ER': 'Eritrea',
    'DJ': 'Djibouti',
    'SO': 'Somalia',
    'MW': 'Malawi',
    'ZM': 'Zambia',
    'ZW': 'Zimbabwe',
    'BW': 'Botswana',
    'NA': 'Namibia',
    'SZ': 'Eswatini',
    'LS': 'Lesotho',
    'MG': 'Madagascar',
    'MU': 'Mauritius',
    'SC': 'Seychelles',
    'KM': 'Comoros',
    'CV': 'Cape Verde',
    'ST': 'São Tomé and Príncipe',
    'GQ': 'Equatorial Guinea',
    'GA': 'Gabon',
    'CG': 'Republic of the Congo',
    'CD': 'Democratic Republic of the Congo',
    'CF': 'Central African Republic',
    'TD': 'Chad',
    'CM': 'Cameroon',
    'BJ': 'Benin',
    'TG': 'Togo',
    'BF': 'Burkina Faso',
    'CI': 'Côte d\'Ivoire',
    'LR': 'Liberia',
    'SL': 'Sierra Leone',
    'GN': 'Guinea',
    'GW': 'Guinea-Bissau',
    'SN': 'Senegal',
    'GM': 'Gambia',
    'ML': 'Mali',
    'MR': 'Mauritania',
    'NE': 'Niger'
  };
  
  return countries[countryCode] || countryCode;
};
